using Microsoft.Extensions.Logging;
using SecurityAgent.Config;
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;

namespace SecurityAgent.Services;

public class EmailService
{
    private readonly HttpClient _http;
    private readonly TokenService _tokenService;
    private readonly AgentConfiguration _config;
    private readonly ILogger<EmailService> _logger;

    public EmailService(
        IHttpClientFactory httpClientFactory,
        TokenService tokenService,
        AgentConfiguration config,
        ILogger<EmailService> logger)
    {
        _http = httpClientFactory.CreateClient();
        _tokenService = tokenService;
        _config = config;
        _logger = logger;
    }

    /// <summary>
    /// Send a notification email with the full HTML report as an attachment.
    /// The email body is a styled notification with a "View Full Report" button
    /// linking to SharePoint, and the HTML file is attached for offline viewing.
    /// </summary>
    public async Task<bool> SendReportWithAttachmentAsync(
        string reportName, string sharePointUrl, string htmlReport,
        string attachmentFileName, string? recipientOverride = null)
    {
        var mailbox = _config.ReportSharedMailbox;
        if (string.IsNullOrEmpty(mailbox))
        {
            _logger.LogWarning("ReportSharedMailbox is not configured, skipping email");
            return false;
        }

        var recipients = recipientOverride ?? _config.ReportRecipients;
        if (string.IsNullOrEmpty(recipients))
        {
            _logger.LogWarning("No report recipients configured, skipping email");
            return false;
        }

        var token = await _tokenService.GetTokenAsync(_config.GraphScope);
        _http.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue("Bearer", token);

        var toRecipients = recipients.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Where(email =>
            {
                // Validate domain restriction
                var domain = _config.OrganizationDomain;
                if (!string.IsNullOrEmpty(domain) && !email.EndsWith($"@{domain}", StringComparison.OrdinalIgnoreCase))
                {
                    _logger.LogWarning("Blocked email to external address: {Email} (only @{Domain} allowed)", email, domain);
                    return false;
                }
                return true;
            })
            .Select(email => new
            {
                emailAddress = new { address = email }
            }).ToArray();

        if (toRecipients.Length == 0)
        {
            _logger.LogWarning("No valid recipients after domain filtering");
            return false;
        }

        // Build notification email body with inline styles (email-safe)
        var encodedName = System.Net.WebUtility.HtmlEncode(reportName);
        var encodedUrl = System.Net.WebUtility.HtmlEncode(sharePointUrl);
        var hasSharePointLink = !string.IsNullOrEmpty(sharePointUrl) && !sharePointUrl.StartsWith("Error");

        var viewButton = hasSharePointLink
            ? $"<a href=\"{encodedUrl}\" style=\"display:inline-block;background:#0061ad;color:white;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600;font-family:'Segoe UI',Arial,sans-serif;\">View on SharePoint</a>"
            : "";
        var sharePointNote = hasSharePointLink
            ? "<p style=\"margin-top:16px;font-size:12px;color:#6c757d;font-family:'Segoe UI',Arial,sans-serif;\">This report is also available on the IT SharePoint site.</p>"
            : "";

        var emailBody = "<html><body style=\"margin:0;padding:0;background:#f8f9fa;\">" +
            "<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"max-width:600px;margin:0 auto;\">" +
            "<tr><td style=\"background:linear-gradient(135deg,#0061ad,#004a85);padding:24px 32px;color:white;\">" +
            $"<h1 style=\"margin:0;font-size:22px;font-weight:600;font-family:'Segoe UI',Arial,sans-serif;color:white;\">{encodedName}</h1>" +
            "<p style=\"margin:4px 0 0;opacity:0.8;font-size:14px;font-family:'Segoe UI',Arial,sans-serif;color:white;\">Generated by Security Agent</p>" +
            "</td></tr>" +
            "<tr><td style=\"padding:24px 32px;background:white;border:1px solid #eef0f2;border-top:none;\">" +
            $"<p style=\"font-family:'Segoe UI',Arial,sans-serif;color:#3a4149;font-size:14px;\">Your biweekly <strong>{encodedName}</strong> has been generated. The full report is attached as an HTML file — open it in your browser for the best viewing experience.</p>" +
            $"<div style=\"margin-top:24px;\">{viewButton}</div>" +
            sharePointNote +
            "</td></tr></table></body></html>";

        // Base64 encode the HTML attachment
        var attachmentBytes = Encoding.UTF8.GetBytes(htmlReport);
        var attachmentBase64 = Convert.ToBase64String(attachmentBytes);

        // Build message using Dictionary to properly handle @odata.type
        var attachment = new Dictionary<string, object>
        {
            ["@odata.type"] = "#microsoft.graph.fileAttachment",
            ["name"] = attachmentFileName,
            ["contentType"] = "text/html",
            ["contentBytes"] = attachmentBase64
        };

        var messagePayload = new Dictionary<string, object>
        {
            ["message"] = new Dictionary<string, object>
            {
                ["subject"] = $"Security Report: {reportName}",
                ["body"] = new Dictionary<string, object>
                {
                    ["contentType"] = "HTML",
                    ["content"] = emailBody
                },
                ["toRecipients"] = toRecipients.Select(r => new Dictionary<string, object>
                {
                    ["emailAddress"] = new Dictionary<string, string> { ["address"] = r.emailAddress.address }
                }).ToArray(),
                ["from"] = new Dictionary<string, object>
                {
                    ["emailAddress"] = new Dictionary<string, string> { ["address"] = mailbox }
                },
                ["attachments"] = new[] { attachment }
            },
            ["saveToSentItems"] = true
        };

        var url = $"{_config.GraphBaseUrl}/users/{mailbox}/sendMail";
        var json = JsonSerializer.Serialize(messagePayload);
        var content = new StringContent(json, Encoding.UTF8, "application/json");

        _logger.LogInformation("Sending report email with attachment from {Mailbox} to {Recipients}", mailbox, recipients);

        try
        {
            var response = await _http.PostAsync(url, content);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync();
                _logger.LogError("Failed to send email: {Status} {Content}",
                    response.StatusCode, errorContent);
                return false;
            }

            _logger.LogInformation("Report email sent successfully with attachment {FileName}", attachmentFileName);
            return true;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error sending report email");
            return false;
        }
    }
}
