using Microsoft.Extensions.Logging;
using SecurityAgent.Config;
using System.Text;
using System.Text.Json;

namespace SecurityAgent.Services;

public class ReportGeneratorService
{
    private readonly IntuneService _intune;
    private readonly GraphApiService _graph;
    private readonly DefenderApiService _defender;
    private readonly AdvancedHuntingService _hunting;
    private readonly AgentConfiguration _config;
    private readonly ILogger<ReportGeneratorService> _logger;

    public ReportGeneratorService(
        IntuneService intune,
        GraphApiService graph,
        DefenderApiService defender,
        AdvancedHuntingService hunting,
        AgentConfiguration config,
        ILogger<ReportGeneratorService> logger)
    {
        _intune = intune;
        _graph = graph;
        _defender = defender;
        _hunting = hunting;
        _config = config;
        _logger = logger;
    }

    // ═══════════════════════════════════════════════════════════════
    // REPORT 1: DEVICES & VULNERABILITIES
    // ═══════════════════════════════════════════════════════════════

    public async Task<string> GenerateDevicesReportAsync()
    {
        _logger.LogInformation("Generating Devices & Vulnerabilities Report");

        // Gather all data in parallel where possible
        var complianceTask = _intune.GetDeviceComplianceSummaryAsync();
        var noncompliantTask = _intune.GetNoncompliantDevicesAsync();
        var updateRingsTask = _intune.GetWindowsUpdateRingsAsync();
        var updateStatusTask = _intune.GetWindowsUpdateStatusAsync();
        var staleTask = _intune.GetStaleDevicesAsync(30);

        // Vulnerabilities via Advanced Hunting — per-device breakdown + overall summary
        var vulnParams = new Dictionary<string, string>
        {
            ["severity_filter"] = "\"Critical\", \"High\""
        };
        var vulnTask = _hunting.RunTemplateQueryAsync("search_device_vulnerabilities", vulnParams);
        var vulnSummaryTask = _hunting.RunTemplateQueryAsync("search_vulnerability_summary", new Dictionary<string, string>());

        await Task.WhenAll(complianceTask, noncompliantTask, updateRingsTask, updateStatusTask, staleTask, vulnTask, vulnSummaryTask);

        var complianceJson = await complianceTask;
        var noncompliantJson = await noncompliantTask;
        var updateRingsJson = await updateRingsTask;
        var updateStatusJson = await updateStatusTask;
        var staleJson = await staleTask;
        var vulnJson = await vulnTask;
        var vulnSummaryJson = await vulnSummaryTask;

        // Parse the data
        var compliance = ParseComplianceSummary(complianceJson);
        var noncompliantDevices = ParseNoncompliantDevices(noncompliantJson);
        var updateRings = ParseUpdateRings(updateRingsJson);
        var updateStatus = ParseUpdateStatus(updateStatusJson);
        var staleDevices = ParseStaleDevices(staleJson);
        var vulnerabilities = ParseVulnerabilities(vulnJson);
        var vulnSummary = ParseVulnSummary(vulnSummaryJson);

        // Get report period
        var now = GetAtlanticTime();
        var periodEnd = now;
        var periodStart = now.AddDays(-14);
        var periodString = $"{periodStart:MMMM d} – {periodEnd:MMMM d, yyyy}";
        var timeZone = IsAtlanticDaylightTime(now) ? "ADT" : "AST";

        var sb = new StringBuilder();
        sb.Append(GetHtmlHead("SFI Devices & Vulnerabilities Report"));
        sb.Append(GetHeader("Devices & Vulnerabilities Report",
            "Biweekly security posture summary — generated by SFI Security Agent", periodString));

        // Stats bar
        sb.Append("<div class=\"stats-bar\">");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number green\">{compliance.Compliant}</div><div class=\"stat-label\">Compliant</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number red\">{compliance.Noncompliant}</div><div class=\"stat-label\">Noncompliant</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number orange\">{vulnSummary.Total}</div><div class=\"stat-label\">Vulnerabilities</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number blue\">{staleDevices.Count}</div><div class=\"stat-label\">Stale Devices</div></div>");
        sb.Append("</div>");

        // Device Compliance Section
        int total = compliance.Compliant + compliance.Noncompliant + compliance.Unknown;
        int compliantPct = total > 0 ? (int)Math.Round(100.0 * compliance.Compliant / total) : 0;
        int noncompliantPct = total > 0 ? 100 - compliantPct : 0;

        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon blue\">🛡️</div><div class=\"section-title\">Device Compliance</div></div>");
        sb.Append($"<div class=\"section-summary\">{total} managed devices — {compliance.Compliant} compliant, {compliance.Noncompliant} noncompliant.</div>");
        sb.Append($"<div class=\"compliance-bar\"><div class=\"compliant\" style=\"width:{compliantPct}%\"></div><div class=\"noncompliant\" style=\"width:{noncompliantPct}%\"></div></div>");
        sb.Append("<div class=\"compliance-legend\">");
        sb.Append($"<div class=\"legend-item\"><div class=\"legend-dot green\"></div> Compliant ({compliantPct}%)</div>");
        sb.Append($"<div class=\"legend-item\"><div class=\"legend-dot red\"></div> Noncompliant ({noncompliantPct}%)</div>");
        sb.Append("</div>");

        // Noncompliant devices table
        sb.Append("<table><thead><tr><th>Device Name</th><th>OS</th><th>OS Version</th><th>User</th><th>Status</th><th>Last Sync (" + timeZone + ")</th></tr></thead><tbody>");
        foreach (var d in noncompliantDevices)
        {
            var syncTime = ConvertToAtlantic(d.LastSync);
            sb.Append($"<tr><td>{Esc(d.DeviceName)}</td><td>{Esc(d.Os)}</td><td class=\"mono\">{Esc(d.OsVersion)}</td>");
            sb.Append($"<td>{Esc(d.User)}</td><td><span class=\"badge badge-noncompliant\">Noncompliant</span></td>");
            sb.Append($"<td>{syncTime}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Vulnerabilities Section — portal-style summary cards
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon red\">🔓</div><div class=\"section-title\">Vulnerabilities</div></div>");
        sb.Append($"<div class=\"section-summary\">{vulnSummary.Total} unique vulnerabilities across {vulnSummary.AffectedDevices} devices.</div>");

        // Vulnerability summary cards (like Defender portal)
        sb.Append("<div class=\"ring-cards\" style=\"grid-template-columns: repeat(3, 1fr); margin-bottom: 20px;\">");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Total Vulnerabilities</span><span style=\"font-weight:700;font-size:20px;color:var(--sfi-blue)\">{vulnSummary.Total}</span></div></div>");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Exploitable</span><span style=\"font-weight:700;font-size:20px;color:var(--sfi-orange)\">{vulnSummary.Exploitable}</span></div></div>");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Zero-Day</span><span style=\"font-weight:700;font-size:20px;color:var(--sfi-red)\">{vulnSummary.ZeroDay}</span></div></div>");
        sb.Append("</div>");
        sb.Append("<div class=\"ring-cards\" style=\"grid-template-columns: repeat(4, 1fr); margin-bottom: 20px;\">");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Critical</span><span style=\"font-weight:700;color:var(--sfi-red)\">{vulnSummary.Critical}</span></div></div>");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">High</span><span style=\"font-weight:700;color:var(--sfi-orange)\">{vulnSummary.High}</span></div></div>");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">With Security Update</span><span style=\"font-weight:700;color:var(--sfi-green)\">{vulnSummary.WithUpdate}</span></div></div>");
        sb.Append($"<div class=\"ring-card\"><div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">No Security Update</span><span style=\"font-weight:700;color:var(--sfi-red)\">{vulnSummary.WithoutUpdate}</span></div></div>");
        sb.Append("</div>");

        // Per-device vulnerability table
        sb.Append("<table><thead><tr><th>Device</th><th>Top CVEs</th><th>Max CVSS</th><th>Unique CVEs</th><th>Software Affected</th></tr></thead><tbody>");
        foreach (var v in vulnerabilities.OrderByDescending(x => x.MaxCvss).Take(50))
        {
            var severityClass = v.MaxCvss >= 9.0 ? "critical" : v.MaxCvss >= 7.0 ? "high" : "medium";
            var topCves = string.Join(", ", v.CveIds.Take(3));
            if (v.CveIds.Count > 3) topCves += $" (+{v.CveIds.Count - 3} more)";
            var software = string.Join(", ", v.Software.Take(3));

            sb.Append($"<tr><td>{Esc(v.DeviceName)}</td><td class=\"mono\">{Esc(topCves)}</td>");
            sb.Append($"<td><span class=\"badge badge-{severityClass}\"><strong>{v.MaxCvss:F1}</strong></span></td>");
            sb.Append($"<td>{v.CveIds.Count}</td><td>{Esc(software)}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Windows Update Section — use update status data
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon green\">🔄</div><div class=\"section-title\">Windows Update Status</div></div>");
        sb.Append("<div class=\"section-summary\">Update ring compliance across managed Windows devices.</div>");
        if (updateStatus.DeviceCount > 0)
        {
            // Show overall status card
            sb.Append("<div class=\"ring-cards\" style=\"margin-bottom: 16px;\">");
            sb.Append("<div class=\"ring-card\">");
            sb.Append("<div class=\"ring-card-title\">Overall Update Status</div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Device Count</span><span style=\"font-weight:600\">{updateStatus.DeviceCount}</span></div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Up to Date</span><span style=\"font-weight:600;color:var(--sfi-green)\">{updateStatus.CompliantCount}</span></div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Not Up to Date</span><span style=\"font-weight:600;color:var(--sfi-orange)\">{updateStatus.NonCompliantCount}</span></div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">In Progress</span><span style=\"font-weight:600;color:var(--sfi-blue)\">{updateStatus.PendingCount}</span></div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Not Ready</span><span style=\"font-weight:600;color:var(--sfi-red)\">{updateStatus.ErrorCount}</span></div>");
            sb.Append("</div>");
            sb.Append("</div>");
        }
        // Show ring configurations
        sb.Append("<div class=\"ring-cards\">");
        foreach (var ring in updateRings)
        {
            sb.Append("<div class=\"ring-card\">");
            sb.Append($"<div class=\"ring-card-title\">{Esc(ring.Name)}</div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Deferral (Quality)</span><span style=\"font-weight:600\">{ring.QualityDeferral} days</span></div>");
            sb.Append($"<div class=\"ring-stat-row\"><span style=\"color:var(--sfi-gray-500)\">Deferral (Feature)</span><span style=\"font-weight:600\">{ring.FeatureDeferral} days</span></div>");
            sb.Append("</div>");
        }
        sb.Append("</div></div>");

        // Stale Devices Section
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon orange\">📱</div><div class=\"section-title\">Stale Devices</div></div>");
        sb.Append($"<div class=\"section-summary\">{staleDevices.Count} devices have not synced in over 30 days.</div>");
        sb.Append("<table><thead><tr><th>Device Name</th><th>User</th><th>Last Sync (" + timeZone + ")</th><th>Days Inactive</th><th>Compliance</th></tr></thead><tbody>");
        foreach (var d in staleDevices.OrderByDescending(x => x.DaysInactive))
        {
            var color = d.DaysInactive > 180 ? "var(--sfi-red)" : "var(--sfi-orange)";
            var syncTime = ConvertToAtlantic(d.LastSync);
            sb.Append($"<tr><td>{Esc(d.DeviceName)}</td><td>{Esc(d.User)}</td><td>{syncTime}</td>");
            sb.Append($"<td style=\"font-weight:700;color:{color}\">{d.DaysInactive}</td>");
            sb.Append($"<td><span class=\"badge badge-noncompliant\">Noncompliant</span></td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Footer
        sb.Append(GetFooter("Devices & Vulnerabilities Report", now, timeZone));
        sb.Append("</body></html>");

        _logger.LogInformation("Devices & Vulnerabilities Report generated successfully");
        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════════
    // REPORT 2: SHAREPOINT & EXTERNAL ACCESS
    // ═══════════════════════════════════════════════════════════════

    public async Task<string> GenerateSharePointReportAsync()
    {
        _logger.LogInformation("Generating SharePoint & External Access Report");

        var now = GetAtlanticTime();
        var periodStart = now.AddDays(-14);
        var startDate = periodStart.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");
        var endDate = now.ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ");

        // Gather data
        var guestTask = _graph.GetGuestUsersAsync();
        var sharingParams = new Dictionary<string, string>
        {
            ["start_date"] = startDate,
            ["end_date"] = endDate
        };
        var sharingTask = _hunting.RunTemplateQueryAsync("search_external_sharing", sharingParams);

        await Task.WhenAll(guestTask, sharingTask);

        var guestJson = await guestTask;
        var sharingJson = await sharingTask;

        var guests = ParseGuestUsers(guestJson);
        var sharingEvents = ParseSharingEvents(sharingJson);

        var periodString = $"{periodStart:MMMM d} – {now:MMMM d, yyyy}";
        var timeZone = IsAtlanticDaylightTime(now) ? "ADT" : "AST";

        // Count anonymous links
        int anonymousLinks = sharingEvents.Count(e =>
            e.ActionType.Contains("Anonymous", StringComparison.OrdinalIgnoreCase));
        int pendingGuests = guests.Count(g =>
            g.ExternalUserState?.Equals("PendingAcceptance", StringComparison.OrdinalIgnoreCase) == true
            || string.IsNullOrEmpty(g.ExternalUserState));

        // Expiring access — guests inactive 60+ days or still pending
        var expiringGuests = guests.Where(g =>
            g.ExternalUserState?.Equals("PendingAcceptance", StringComparison.OrdinalIgnoreCase) == true
            || string.IsNullOrEmpty(g.ExternalUserState)
            || (g.LastSignIn.HasValue && (now.ToUniversalTime() - g.LastSignIn.Value).TotalDays > 60)
            || (!g.LastSignIn.HasValue && g.CreatedDate.HasValue && (now.ToUniversalTime() - g.CreatedDate.Value).TotalDays > 60)
        ).ToList();

        var sb = new StringBuilder();
        sb.Append(GetHtmlHead("SFI SharePoint & External Access Report"));
        sb.Append(GetHeader("SharePoint & External Access Report",
            "Biweekly external access review — generated by SFI Security Agent", periodString));

        // Stats bar
        sb.Append("<div class=\"stats-bar\">");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number blue\">{guests.Count}</div><div class=\"stat-label\">Guest Users</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number orange\">{sharingEvents.Count}</div><div class=\"stat-label\">External Shares</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number red\">{anonymousLinks}</div><div class=\"stat-label\">Anonymous Links</div></div>");
        sb.Append($"<div class=\"stat-item\"><div class=\"stat-number orange\">{expiringGuests.Count}</div><div class=\"stat-label\">Expiring Access</div></div>");
        sb.Append("</div>");

        // External Sharing Section
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon yellow\">🔗</div><div class=\"section-title\">External Sharing Activity</div></div>");
        sb.Append($"<div class=\"section-summary\">{sharingEvents.Count} external sharing events in the past 2 weeks.</div>");

        if (anonymousLinks > 0)
        {
            sb.Append($"<div class=\"alert-box\">⚠️ <strong>{anonymousLinks} anonymous link{(anonymousLinks > 1 ? "s" : "")}</strong> created. Anonymous links allow anyone with the link to access the file without authentication.</div>");
        }

        sb.Append("<table><thead><tr><th>Date (" + timeZone + ")</th><th>Shared By</th><th>File / Folder</th><th>Shared With</th><th>Site</th><th>Type</th></tr></thead><tbody>");
        foreach (var e in sharingEvents.Take(100))
        {
            var date = ConvertToAtlantic(e.Timestamp);
            var badgeClass = e.ActionType.Contains("Anonymous", StringComparison.OrdinalIgnoreCase) ? "badge-high" : "badge-info";
            var typeLabel = e.ActionType.Contains("Anonymous", StringComparison.OrdinalIgnoreCase) ? "Anonymous Link" : "Specific People";
            sb.Append($"<tr><td>{date}</td><td>{Esc(e.User)}</td><td>{Esc(TruncateFileName(e.ItemName))}</td>");
            sb.Append($"<td>{Esc(e.SharedWith)}</td><td>{Esc(ShortenSiteUrl(e.SiteUrl))}</td>");
            sb.Append($"<td><span class=\"badge {badgeClass}\">{typeLabel}</span></td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Guest Users Section
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon blue\">👤</div><div class=\"section-title\">Guest Users</div></div>");
        sb.Append($"<div class=\"section-summary\">{guests.Count} guest users in the tenant. {pendingGuests} have not accepted their invitation.</div>");
        sb.Append("<table><thead><tr><th>Name</th><th>Email</th><th>Company</th><th>Status</th><th>Created</th><th>Last Active</th></tr></thead><tbody>");
        foreach (var g in guests)
        {
            var statusBadge = g.ExternalUserState?.Equals("Accepted", StringComparison.OrdinalIgnoreCase) == true
                ? "<span class=\"badge badge-compliant\">Accepted</span>"
                : "<span class=\"badge badge-noncompliant\">Pending</span>";
            var created = g.CreatedDate?.ToString("yyyy-MM-dd") ?? "—";
            var lastActive = g.LastSignIn.HasValue ? g.LastSignIn.Value.ToString("yyyy-MM-dd") : "Never";

            sb.Append($"<tr><td>{Esc(g.DisplayName)}</td><td>{Esc(g.Email)}</td><td>{Esc(g.Company)}</td>");
            sb.Append($"<td>{statusBadge}</td><td>{created}</td><td>{lastActive}</td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Expiring Guest Access Section
        sb.Append("<div class=\"section\">");
        sb.Append("<div class=\"section-header\"><div class=\"section-icon red\">⏰</div><div class=\"section-title\">Expiring Guest Access</div></div>");
        sb.Append("<div class=\"section-summary\">Guest users inactive for 60+ days or with pending invitations.</div>");

        if (expiringGuests.Any(g => g.ExternalUserState?.Equals("PendingAcceptance", StringComparison.OrdinalIgnoreCase) == true || string.IsNullOrEmpty(g.ExternalUserState)))
        {
            var pendingCount = expiringGuests.Count(g => g.ExternalUserState?.Equals("PendingAcceptance", StringComparison.OrdinalIgnoreCase) == true || string.IsNullOrEmpty(g.ExternalUserState));
            sb.Append($"<div class=\"alert-box red\">🔴 <strong>{pendingCount} guest account{(pendingCount > 1 ? "s" : "")}</strong> have pending invitations that may need to be resent or removed.</div>");
        }

        sb.Append("<table><thead><tr><th>Name</th><th>Email</th><th>Created</th><th>Last Active</th><th>Days Since Activity</th><th>Recommendation</th></tr></thead><tbody>");
        foreach (var g in expiringGuests)
        {
            var created = g.CreatedDate?.ToString("yyyy-MM-dd") ?? "—";
            var lastActive = g.LastSignIn.HasValue ? g.LastSignIn.Value.ToString("yyyy-MM-dd") : "Never";
            int daysSince;
            string recommendation;
            string badgeClass;

            if (!g.LastSignIn.HasValue)
            {
                daysSince = g.CreatedDate.HasValue ? (int)(now.ToUniversalTime() - g.CreatedDate.Value).TotalDays : 0;
                recommendation = "Resend or Remove";
                badgeClass = "badge-high";
            }
            else
            {
                daysSince = (int)(now.ToUniversalTime() - g.LastSignIn.Value).TotalDays;
                recommendation = daysSince > 90 ? "Review & Remove" : "Monitor";
                badgeClass = daysSince > 90 ? "badge-high" : "badge-medium";
            }

            var daysColor = daysSince > 90 ? "var(--sfi-red)" : "var(--sfi-orange)";
            var daysLabel = !g.LastSignIn.HasValue ? $"{daysSince} (pending)" : daysSince.ToString();

            sb.Append($"<tr><td>{Esc(g.DisplayName)}</td><td>{Esc(g.Email)}</td><td>{created}</td><td>{lastActive}</td>");
            sb.Append($"<td style=\"font-weight:700;color:{daysColor}\">{daysLabel}</td>");
            sb.Append($"<td><span class=\"badge {badgeClass}\">{recommendation}</span></td></tr>");
        }
        sb.Append("</tbody></table></div>");

        // Footer
        sb.Append(GetFooter("SharePoint & External Access Report", now, timeZone));
        sb.Append("</body></html>");

        _logger.LogInformation("SharePoint & External Access Report generated successfully");
        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════════
    // HTML TEMPLATE COMPONENTS
    // ═══════════════════════════════════════════════════════════════

    private static readonly string CssStyles = @"
      @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
      :root {
        --sfi-blue: #0061ad; --sfi-blue-dark: #004a85; --sfi-blue-light: #e6f0fa;
        --sfi-green: #85c559; --sfi-green-light: #edf7e4;
        --sfi-red: #d13438; --sfi-red-light: #fce8e8;
        --sfi-orange: #ff8c00; --sfi-orange-light: #fff3e0;
        --sfi-yellow: #ffc107; --sfi-yellow-light: #fff8e1;
        --sfi-gray-50: #f8f9fa; --sfi-gray-100: #eef0f2; --sfi-gray-200: #d8dce0;
        --sfi-gray-500: #6c757d; --sfi-gray-700: #3a4149; --sfi-gray-900: #1a1e23;
      }
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: 'DM Sans', -apple-system, sans-serif; background: #fff; color: var(--sfi-gray-700); line-height: 1.6; max-width: 1100px; margin: 0 auto; }
      .report-header { background: linear-gradient(135deg, var(--sfi-blue) 0%, var(--sfi-blue-dark) 100%); padding: 36px 48px; color: #fff; position: relative; overflow: hidden; }
      .report-header::after { content: ''; position: absolute; top: -60%; right: -8%; width: 400px; height: 400px; background: rgba(133,197,89,0.06); border-radius: 50%; }
      .header-top { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; position: relative; z-index: 1; }
      .logo-img { height: 56px; }
      .report-date-badge { background: rgba(255,255,255,0.15); padding: 8px 16px; border-radius: 8px; font-size: 13px; font-weight: 500; backdrop-filter: blur(4px); }
      .report-title { font-size: 30px; font-weight: 700; letter-spacing: -0.5px; margin-bottom: 4px; position: relative; z-index: 1; }
      .report-subtitle { font-size: 14px; opacity: 0.75; position: relative; z-index: 1; }
      .stats-bar { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0; border-bottom: 2px solid var(--sfi-gray-100); }
      .stat-item { padding: 22px 28px; text-align: center; border-right: 1px solid var(--sfi-gray-100); }
      .stat-item:last-child { border-right: none; }
      .stat-number { font-size: 34px; font-weight: 700; line-height: 1; margin-bottom: 4px; }
      .stat-number.green { color: var(--sfi-green); } .stat-number.red { color: var(--sfi-red); }
      .stat-number.orange { color: var(--sfi-orange); } .stat-number.blue { color: var(--sfi-blue); }
      .stat-label { font-size: 11px; color: var(--sfi-gray-500); text-transform: uppercase; letter-spacing: 1px; font-weight: 600; }
      .section { padding: 28px 48px; border-bottom: 1px solid var(--sfi-gray-100); }
      .section:last-child { border-bottom: none; }
      .section-header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
      .section-icon { width: 34px; height: 34px; border-radius: 9px; display: flex; align-items: center; justify-content: center; font-size: 17px; }
      .section-icon.blue { background: var(--sfi-blue-light); } .section-icon.red { background: var(--sfi-red-light); }
      .section-icon.green { background: var(--sfi-green-light); } .section-icon.orange { background: var(--sfi-orange-light); }
      .section-icon.yellow { background: var(--sfi-yellow-light); }
      .section-title { font-size: 19px; font-weight: 700; color: var(--sfi-gray-900); }
      .section-summary { font-size: 13px; color: var(--sfi-gray-500); margin-bottom: 14px; }
      table { width: 100%; border-collapse: collapse; font-size: 12.5px; margin: 8px 0; }
      thead th { background: var(--sfi-gray-50); color: var(--sfi-gray-500); font-weight: 600; text-align: left; padding: 9px 12px; border-bottom: 2px solid var(--sfi-gray-200); font-size: 10.5px; text-transform: uppercase; letter-spacing: 0.5px; white-space: nowrap; }
      tbody td { padding: 8px 12px; border-bottom: 1px solid var(--sfi-gray-100); vertical-align: top; }
      tbody tr:hover { background: var(--sfi-gray-50); }
      .badge { display: inline-block; padding: 2px 9px; border-radius: 10px; font-size: 10.5px; font-weight: 600; }
      .badge-critical { background: var(--sfi-red-light); color: var(--sfi-red); }
      .badge-high { background: var(--sfi-orange-light); color: var(--sfi-orange); }
      .badge-medium { background: var(--sfi-yellow-light); color: #b38600; }
      .badge-low { background: var(--sfi-green-light); color: #4a8c20; }
      .badge-info { background: var(--sfi-blue-light); color: var(--sfi-blue); }
      .badge-compliant { background: var(--sfi-green-light); color: #4a8c20; }
      .badge-noncompliant { background: var(--sfi-red-light); color: var(--sfi-red); }
      .compliance-bar { height: 12px; border-radius: 6px; overflow: hidden; display: flex; background: var(--sfi-gray-100); margin: 12px 0; }
      .compliance-bar .compliant { background: var(--sfi-green); } .compliance-bar .noncompliant { background: var(--sfi-red); }
      .compliance-legend { display: flex; gap: 24px; margin-bottom: 14px; font-size: 12px; }
      .legend-item { display: flex; align-items: center; gap: 6px; }
      .legend-dot { width: 10px; height: 10px; border-radius: 50%; }
      .legend-dot.green { background: var(--sfi-green); } .legend-dot.red { background: var(--sfi-red); }
      .mono { font-family: 'JetBrains Mono', monospace; font-size: 11.5px; }
      .remediation { font-family: 'JetBrains Mono', monospace; font-size: 11px; color: var(--sfi-gray-500); }
      .ring-cards { display: grid; grid-template-columns: repeat(2, 1fr); gap: 14px; margin-top: 8px; }
      .ring-card { border: 1px solid var(--sfi-gray-200); border-radius: 10px; padding: 18px; background: var(--sfi-gray-50); }
      .ring-card-title { font-weight: 700; font-size: 14px; color: var(--sfi-gray-900); margin-bottom: 10px; }
      .ring-stat-row { display: flex; justify-content: space-between; padding: 5px 0; font-size: 12.5px; border-bottom: 1px solid var(--sfi-gray-100); }
      .ring-stat-row:last-child { border-bottom: none; }
      .alert-box { border-left: 4px solid var(--sfi-orange); background: var(--sfi-orange-light); padding: 12px 16px; border-radius: 0 8px 8px 0; margin-bottom: 16px; font-size: 13px; }
      .alert-box.red { border-left-color: var(--sfi-red); background: var(--sfi-red-light); }
      .report-footer { padding: 22px 48px; background: var(--sfi-gray-50); border-top: 2px solid var(--sfi-gray-100); text-align: center; font-size: 11.5px; color: var(--sfi-gray-500); }
      .footer-brand { font-weight: 600; color: var(--sfi-blue); }
    ";

    private string GetHtmlHead(string title) =>
        "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n" +
        "<meta charset=\"UTF-8\">\n" +
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
        $"<title>{Esc(title)}</title>\n" +
        $"<style>{CssStyles}</style>\n" +
        "</head>\n<body>\n";

    private string GetHeader(string title, string subtitle, string period)
    {
        var logoSrc = !string.IsNullOrEmpty(_config.ReportLogoSvgBase64)
            ? $"data:image/svg+xml;base64,{_config.ReportLogoSvgBase64}"
            : "";
        var logoImg = !string.IsNullOrEmpty(logoSrc)
            ? $"<img src=\"{logoSrc}\" alt=\"Strongest Families Institute\" class=\"logo-img\">"
            : "<div style=\"font-size:18px;font-weight:700\">Strongest Families Institute</div>";

        return "<div class=\"report-header\">\n" +
            "  <div class=\"header-top\">\n" +
            $"    {logoImg}\n" +
            $"    <div class=\"report-date-badge\">{Esc(period)}</div>\n" +
            "  </div>\n" +
            $"  <div class=\"report-title\">{Esc(title)}</div>\n" +
            $"  <div class=\"report-subtitle\">{Esc(subtitle)}</div>\n" +
            "</div>\n";
    }

    private static string GetFooter(string reportName, DateTime now, string tz) =>
        "<div class=\"report-footer\">\n" +
        $"  <span class=\"footer-brand\">Strongest Families Institute</span> — {reportName}<br>\n" +
        $"  Generated on {now:MMMM d, yyyy} at {now:h:mm tt} {tz} by SFI Security Agent\n" +
        "</div>\n";

    // ═══════════════════════════════════════════════════════════════
    // DATA PARSING HELPERS
    // ═══════════════════════════════════════════════════════════════

    private record ComplianceSummary(int Compliant, int Noncompliant, int Unknown);

    private ComplianceSummary ParseComplianceSummary(string json)
    {
        int compliant = 0, noncompliant = 0, unknown = 0;
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;

            // The compliance summary returns a flat object with totalDevices, compliant, noncompliant, etc.
            if (root.TryGetProperty("compliant", out var c))
                compliant = c.GetInt32();
            if (root.TryGetProperty("noncompliant", out var nc))
                noncompliant = nc.GetInt32();
            if (root.TryGetProperty("unknown", out var unk))
                unknown = unk.GetInt32();
            if (root.TryGetProperty("inGracePeriod", out var igp))
                unknown += igp.GetInt32();
            if (root.TryGetProperty("configManager", out var cm))
                unknown += cm.GetInt32();
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse compliance summary");
        }
        return new ComplianceSummary(compliant, noncompliant, unknown);
    }

    private record DeviceInfo(string DeviceName, string Os, string OsVersion, string User, DateTime? LastSync);

    private List<DeviceInfo> ParseNoncompliantDevices(string json)
    {
        var devices = new List<DeviceInfo>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("value", out var values))
            {
                foreach (var item in values.EnumerateArray())
                {
                    devices.Add(new DeviceInfo(
                        DeviceName: item.GetProperty("deviceName").GetString() ?? "Unknown",
                        Os: item.TryGetProperty("operatingSystem", out var os) ? os.GetString() ?? "" : "",
                        OsVersion: item.TryGetProperty("osVersion", out var ov) ? ov.GetString() ?? "" : "",
                        User: item.TryGetProperty("userPrincipalName", out var upn) ? upn.GetString() ?? "(no user)" : "(no user)",
                        LastSync: item.TryGetProperty("lastSyncDateTime", out var ls) && ls.ValueKind != JsonValueKind.Null
                            ? DateTime.Parse(ls.GetString()!) : null
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse noncompliant devices");
        }
        return devices;
    }

    private record VulnInfo(string DeviceName, List<string> CveIds, double MaxCvss, int TotalVulns, List<string> Software);

    private List<VulnInfo> ParseVulnerabilities(string json)
    {
        var vulns = new List<VulnInfo>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("results", out var results))
            {
                foreach (var item in results.EnumerateArray())
                {
                    var cves = new List<string>();
                    var software = new List<string>();
                    if (item.TryGetProperty("CVEs", out var cveProp))
                    {
                        if (cveProp.ValueKind == JsonValueKind.Array)
                            cves = cveProp.EnumerateArray().Select(c => c.GetString() ?? "").ToList();
                        else if (cveProp.ValueKind == JsonValueKind.String)
                            cves = JsonSerializer.Deserialize<List<string>>(cveProp.GetString()!) ?? new();
                    }
                    if (item.TryGetProperty("Software", out var swProp))
                    {
                        if (swProp.ValueKind == JsonValueKind.Array)
                            software = swProp.EnumerateArray().Select(s => s.GetString() ?? "").ToList();
                        else if (swProp.ValueKind == JsonValueKind.String)
                            software = JsonSerializer.Deserialize<List<string>>(swProp.GetString()!) ?? new();
                    }

                    vulns.Add(new VulnInfo(
                        DeviceName: item.TryGetProperty("DeviceName", out var dn) ? dn.GetString() ?? "" : "",
                        CveIds: cves,
                        MaxCvss: item.TryGetProperty("MaxCVSS", out var mc) ? mc.GetDouble() : 0,
                        TotalVulns: item.TryGetProperty("TotalVulns", out var tv) ? tv.GetInt32() : 0,
                        Software: software
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse vulnerabilities");
        }
        return vulns;
    }

    private record VulnSummaryInfo(int Total, int Critical, int High, int Medium, int Low,
        int Exploitable, int ZeroDay, int WithUpdate, int WithoutUpdate, int AffectedDevices);

    private VulnSummaryInfo ParseVulnSummary(string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("results", out var results) && results.GetArrayLength() > 0)
            {
                var row = results[0];
                return new VulnSummaryInfo(
                    Total: GetIntProp(row, "TotalVulnerabilities"),
                    Critical: GetIntProp(row, "CriticalVulnerabilities"),
                    High: GetIntProp(row, "HighVulnerabilities"),
                    Medium: GetIntProp(row, "MediumVulnerabilities"),
                    Low: GetIntProp(row, "LowVulnerabilities"),
                    Exploitable: GetIntProp(row, "ExploitableVulnerabilities"),
                    ZeroDay: GetIntProp(row, "ZeroDayVulnerabilities"),
                    WithUpdate: GetIntProp(row, "VulnsWithSecurityUpdate"),
                    WithoutUpdate: GetIntProp(row, "VulnsWithoutSecurityUpdate"),
                    AffectedDevices: GetIntProp(row, "AffectedDevices")
                );
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse vulnerability summary");
        }
        return new VulnSummaryInfo(0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    }

    private static int GetIntProp(JsonElement el, string name)
    {
        if (el.TryGetProperty(name, out var val))
        {
            if (val.ValueKind == JsonValueKind.Number) return val.GetInt32();
            if (val.ValueKind == JsonValueKind.String && int.TryParse(val.GetString(), out var parsed)) return parsed;
        }
        return 0;
    }

    private record UpdateStatusInfo(int DeviceCount, int CompliantCount, int NonCompliantCount, int PendingCount, int ErrorCount);

    private UpdateStatusInfo ParseUpdateStatus(string json)
    {
        try
        {
            using var doc = JsonDocument.Parse(json);
            var root = doc.RootElement;
            // softwareUpdateStatusSummary returns properties directly
            return new UpdateStatusInfo(
                DeviceCount: root.TryGetProperty("compliantDeviceCount", out var cd) ? cd.GetInt32() : 0
                    + (root.TryGetProperty("nonCompliantDeviceCount", out var ncd2) ? ncd2.GetInt32() : 0)
                    + (root.TryGetProperty("errorDeviceCount", out var ed2) ? ed2.GetInt32() : 0)
                    + (root.TryGetProperty("pendingInstallDeviceCount", out var pid2) ? pid2.GetInt32() : 0)
                    + (root.TryGetProperty("notApplicableDeviceCount", out var _na) ? _na.GetInt32() : 0),
                CompliantCount: root.TryGetProperty("compliantDeviceCount", out var cdc) ? cdc.GetInt32() : 0,
                NonCompliantCount: root.TryGetProperty("nonCompliantDeviceCount", out var ncd) ? ncd.GetInt32() : 0,
                PendingCount: root.TryGetProperty("pendingInstallDeviceCount", out var pid) ? pid.GetInt32() : 0,
                ErrorCount: root.TryGetProperty("errorDeviceCount", out var ed) ? ed.GetInt32() : 0
            );
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse update status");
        }
        return new UpdateStatusInfo(0, 0, 0, 0, 0);
    }

    private record UpdateRingInfo(string Name, int QualityDeferral, int FeatureDeferral);

    private List<UpdateRingInfo> ParseUpdateRings(string json)
    {
        var rings = new List<UpdateRingInfo>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("value", out var values))
            {
                foreach (var item in values.EnumerateArray())
                {
                    var name = item.TryGetProperty("displayName", out var dn) ? dn.GetString() ?? "" : "";
                    var qualityDeferral = item.TryGetProperty("qualityUpdatesDeferralPeriodInDays", out var qd) ? qd.GetInt32() : 0;
                    var featureDeferral = item.TryGetProperty("featureUpdatesDeferralPeriodInDays", out var fd) ? fd.GetInt32() : 0;

                    rings.Add(new UpdateRingInfo(name, qualityDeferral, featureDeferral));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse update rings");
        }
        return rings;
    }

    private record StaleDeviceInfo(string DeviceName, string User, DateTime? LastSync, int DaysInactive);

    private List<StaleDeviceInfo> ParseStaleDevices(string json)
    {
        var devices = new List<StaleDeviceInfo>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("value", out var values))
            {
                foreach (var item in values.EnumerateArray())
                {
                    DateTime? lastSync = null;
                    if (item.TryGetProperty("lastSyncDateTime", out var ls) && ls.ValueKind != JsonValueKind.Null)
                        lastSync = DateTime.Parse(ls.GetString()!);

                    var daysInactive = lastSync.HasValue
                        ? (int)(DateTime.UtcNow - lastSync.Value).TotalDays
                        : 999;

                    devices.Add(new StaleDeviceInfo(
                        DeviceName: item.GetProperty("deviceName").GetString() ?? "Unknown",
                        User: item.TryGetProperty("userPrincipalName", out var upn) ? upn.GetString() ?? "(no user)" : "(no user)",
                        LastSync: lastSync,
                        DaysInactive: daysInactive
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse stale devices");
        }
        return devices;
    }

    private record GuestInfo(string DisplayName, string Email, string Company, string? ExternalUserState,
        DateTime? CreatedDate, DateTime? LastSignIn);

    private List<GuestInfo> ParseGuestUsers(string json)
    {
        var guests = new List<GuestInfo>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("value", out var values))
            {
                foreach (var item in values.EnumerateArray())
                {
                    DateTime? lastSignIn = null;
                    if (item.TryGetProperty("signInActivity", out var sia) && sia.ValueKind == JsonValueKind.Object)
                    {
                        if (sia.TryGetProperty("lastSignInDateTime", out var lsi) && lsi.ValueKind != JsonValueKind.Null)
                            lastSignIn = DateTime.Parse(lsi.GetString()!);
                    }

                    var email = item.TryGetProperty("mail", out var m) && m.ValueKind != JsonValueKind.Null
                        ? m.GetString() ?? "" : "";
                    if (string.IsNullOrEmpty(email))
                        email = item.TryGetProperty("userPrincipalName", out var upn) ? upn.GetString() ?? "" : "";

                    guests.Add(new GuestInfo(
                        DisplayName: item.TryGetProperty("displayName", out var dn) ? dn.GetString() ?? "" : "",
                        Email: email,
                        Company: item.TryGetProperty("companyName", out var cn) && cn.ValueKind != JsonValueKind.Null
                            ? cn.GetString() ?? "" : "",
                        ExternalUserState: item.TryGetProperty("externalUserState", out var eus) ? eus.GetString() : null,
                        CreatedDate: item.TryGetProperty("createdDateTime", out var cd) && cd.ValueKind != JsonValueKind.Null
                            ? DateTime.Parse(cd.GetString()!) : null,
                        LastSignIn: lastSignIn
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse guest users");
        }
        return guests;
    }

    private record SharingEvent(DateTime? Timestamp, string User, string ActionType, string ItemName, string SharedWith, string SiteUrl);

    private List<SharingEvent> ParseSharingEvents(string json)
    {
        var events = new List<SharingEvent>();
        try
        {
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.TryGetProperty("results", out var results))
            {
                foreach (var item in results.EnumerateArray())
                {
                    DateTime? ts = null;
                    if (item.TryGetProperty("Timestamp", out var tsProp) && tsProp.ValueKind != JsonValueKind.Null)
                        ts = DateTime.Parse(tsProp.GetString()!);

                    events.Add(new SharingEvent(
                        Timestamp: ts,
                        User: item.TryGetProperty("AccountDisplayName", out var u) ? u.GetString() ?? "" : "",
                        ActionType: item.TryGetProperty("ActionType", out var at) ? at.GetString() ?? "" : "",
                        ItemName: item.TryGetProperty("ItemName", out var itn) ? itn.GetString() ?? "" : "",
                        SharedWith: item.TryGetProperty("SharedWith", out var sw) ? sw.GetString() ?? "" : "",
                        SiteUrl: item.TryGetProperty("SiteUrl", out var su) ? su.GetString() ?? "" : ""
                    ));
                }
            }
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Failed to parse sharing events");
        }
        return events;
    }

    // ═══════════════════════════════════════════════════════════════
    // UTILITY HELPERS
    // ═══════════════════════════════════════════════════════════════

    private static string Esc(string? value) =>
        System.Net.WebUtility.HtmlEncode(value ?? "—");

    private static string ConvertToAtlantic(DateTime? utcDate)
    {
        if (!utcDate.HasValue) return "—";
        var atlantic = GetAtlanticTime(utcDate.Value);
        var tz = IsAtlanticDaylightTime(atlantic) ? "ADT" : "AST";
        return $"{atlantic:yyyy-MM-dd HH:mm}";
    }

    private static DateTime GetAtlanticTime(DateTime? utcDate = null)
    {
        var utc = utcDate ?? DateTime.UtcNow;
        try
        {
            var tz = TimeZoneInfo.FindSystemTimeZoneById("America/Halifax");
            return TimeZoneInfo.ConvertTimeFromUtc(utc.Kind == DateTimeKind.Utc ? utc : DateTime.SpecifyKind(utc, DateTimeKind.Utc), tz);
        }
        catch
        {
            // Fallback: manually calculate AST/ADT
            var offset = IsAtlanticDaylightTime(utc) ? -3 : -4;
            return utc.AddHours(offset);
        }
    }

    private static bool IsAtlanticDaylightTime(DateTime date)
    {
        try
        {
            var tz = TimeZoneInfo.FindSystemTimeZoneById("America/Halifax");
            return tz.IsDaylightSavingTime(date);
        }
        catch
        {
            // Second Sunday of March to first Sunday of November
            var year = date.Year;
            var dstStart = GetNthDayOfWeek(year, 3, DayOfWeek.Sunday, 2).AddHours(2);
            var dstEnd = GetNthDayOfWeek(year, 11, DayOfWeek.Sunday, 1).AddHours(2);
            return date >= dstStart && date < dstEnd;
        }
    }

    private static DateTime GetNthDayOfWeek(int year, int month, DayOfWeek dow, int n)
    {
        var first = new DateTime(year, month, 1);
        var offset = ((int)dow - (int)first.DayOfWeek + 7) % 7;
        return first.AddDays(offset + 7 * (n - 1));
    }

    private static string TruncateFileName(string path)
    {
        if (string.IsNullOrEmpty(path)) return "—";
        var name = path.Contains('/') ? path.Split('/').Last() : path;
        return name.Length > 50 ? name[..47] + "..." : name;
    }

    private static string ShortenSiteUrl(string url)
    {
        if (string.IsNullOrEmpty(url)) return "—";
        // Extract /sites/Name from full URL
        var idx = url.IndexOf("/sites/", StringComparison.OrdinalIgnoreCase);
        if (idx >= 0)
        {
            var rest = url[(idx)..];
            var parts = rest.Split('/', StringSplitOptions.RemoveEmptyEntries);
            return parts.Length >= 2 ? $"/{parts[0]}/{parts[1]}" : rest;
        }
        return url.Length > 40 ? url[..37] + "..." : url;
    }
}
